# **Cargar el Drive Personal**

In [18]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Carga el Dataset de las Firmas**

In [19]:
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/audit_risk.csv')
data

Sector_score  LOCATION_ID  PARA_A  ...  Detection_Risk  Audit_Risk  Risk
0            3.89           23    4.18  ...             0.5      1.7148     1
1            3.89            6    0.00  ...             0.5      0.5108     0
2            3.89            6    0.51  ...             0.5      0.3096     0
3            3.89            6    0.00  ...             0.5      3.5060     1
4            3.89            6    0.00  ...             0.5      0.2832     0
..            ...          ...     ...  ...             ...         ...   ...
771         55.57            9    0.49  ...             0.5      0.3156     0
772         55.57           16    0.47  ...             0.5      0.3136     0
773         55.57           14    0.24  ...             0.5      0.2912     0
774         55.57           18    0.20  ...             0.5      0.2880     0
775         55.57           15    0.00  ...             0.5      0.2928     0

[776 rows x 27 columns]

# **Remover ID's**

In [20]:
mat_feat=data.iloc[:,:-1].values
mat_class=data.iloc[:,-1].values
mat_feat

array([[ 3.89  , 23.    ,  4.18  , ...,  0.4   ,  0.5   ,  1.7148],
       [ 3.89  ,  6.    ,  0.    , ...,  0.4   ,  0.5   ,  0.5108],
       [ 3.89  ,  6.    ,  0.51  , ...,  0.4   ,  0.5   ,  0.3096],
       ...,
       [55.57  , 14.    ,  0.24  , ...,  0.4   ,  0.5   ,  0.2912],
       [55.57  , 18.    ,  0.2   , ...,  0.4   ,  0.5   ,  0.288 ],
       [55.57  , 15.    ,  0.    , ...,  0.4   ,  0.5   ,  0.2928]])

In [21]:
mat_class

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,

# **Imputacion Numerico**

In [22]:
from sklearn.impute import SimpleImputer
import numpy as np
imp=SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(mat_feat[:,:])
mat_feat[:,:]=imp.transform(mat_feat[:,:])


# **Entrenamiento y Prueba**

Se usa el 80% para entrenamiento y el 20% para prueba

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(mat_feat, mat_class, test_size=0.2, random_state=0)


In [24]:
X_train

array([[ 1.85  ,  9.    ,  0.7   , ...,  0.4   ,  0.5   ,  0.3524],
       [ 2.72  , 14.    ,  4.53  , ...,  0.4   ,  0.5   , 21.6724],
       [ 3.41  , 39.    ,  3.63  , ...,  0.4   ,  0.5   ,  1.5948],
       ...,
       [55.57  , 37.    ,  0.49  , ...,  0.4   ,  0.5   ,  0.8732],
       [59.85  ,  4.    ,  0.    , ...,  0.4   ,  0.5   ,  0.28  ],
       [55.57  ,  9.    ,  0.78  , ...,  0.4   ,  0.5   ,  0.3112]])

# **Normalización**

No se recomienda en redes neuronales usar normalización

In [14]:
from sklearn.preprocessing import Normalizer
normal=Normalizer()
X_train[:,:]=normal.fit_transform(X_train[:,:])
X_test[:,:]=normal.fit_transform(X_test[:,:])

Verificar si está normalizado

In [15]:
X_train

array([[0.80938477, 0.58151287, 0.        , ..., 0.00540942, 0.00676178,
        0.0037866 ],
       [0.020948  , 0.1925368 , 0.03411752, ..., 0.00308059, 0.00385074,
        0.10155161],
       [0.25186456, 0.21254393, 0.05313598, ..., 0.12752636, 0.05313598,
        0.14716542],
       ...,
       [0.100519  , 0.7493704 , 0.10956312, ..., 0.01033614, 0.01292018,
        0.07019275],
       [0.01220966, 0.13017648, 0.02199534, ..., 0.00359108, 0.00224442,
        0.206415  ],
       [0.19141095, 0.9349121 , 0.        , ..., 0.01968236, 0.02460295,
        0.01387606]])

In [16]:
X_test

array([[0.07167241, 0.9724397 , 0.02160977, ..., 0.01440651, 0.01800814,
        0.01094895],
       [0.28518777, 0.60937558, 0.        , ..., 0.04875005, 0.06093756,
        0.03412503],
       [0.98144783, 0.15895322, 0.        , ..., 0.00706459, 0.00883073,
        0.00494521],
       ...,
       [0.98261063, 0.14145915, 0.01909699, ..., 0.00707296, 0.0088412 ,
        0.00715783],
       [0.03782861, 0.46592425, 0.04182225, ..., 0.00443737, 0.00554672,
        0.08647998],
       [0.08206268, 0.8428059 , 0.17920715, ..., 0.05322985, 0.0221791 ,
        0.12727256]])

# **Escalado**

Es mejor Escalar

In [25]:
from sklearn.preprocessing import StandardScaler
escala=StandardScaler()
X_train=escala.fit_transform(X_train)
X_test=escala.fit_transform(X_test)
print(X_train)
print(X_test)

[[-0.74574327 -0.6069537  -0.30671327 ... -0.38548548  0.
  -0.30718557]
 [-0.70964548 -0.10640662  0.31438713 ... -0.38548548  0.
   0.84306547]
 [-0.6810162   2.39632877  0.16843664 ... -0.38548548  0.
  -0.24015593]
 ...
 [ 1.48319155  2.19610994 -0.34076838 ... -0.38548548  0.
  -0.2790875 ]
 [ 1.66077608 -1.10750078 -0.42023031 ... -0.38548548  0.
  -0.31109168]
 [ 1.48319155 -0.6069537  -0.29373989 ... -0.38548548  0.
  -0.30940838]]
[[-0.72726784  0.21529502 -0.27445422 ... -0.40693735  0.
  -0.08578336]
 [-0.72726784 -0.45642545  0.03078479 ...  0.60877828  0.
   0.13766898]
 [ 1.52679934 -0.28849533 -0.64074104 ... -0.40693735  0.
  -0.1456785 ]
 ...
 [-0.76880274  0.8870155  -0.43385682 ... -0.40693735  0.
  -0.14384586]
 [-0.75482465  0.71908538  1.02111581 ...  0.60877828  0.
   0.44215349]
 [-0.76880274 -0.23251863 -0.5084708  ... -0.40693735  0.
  -0.14546743]]


# **Red Neuronal con Tensor**

Se instancia la red neuronal y las capas ocultas

In [26]:
import tensorflow as tf
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#segunda capa oculta
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

La capa de salida

In [27]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# **Se entrena la Red Neuronal**

In [28]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [29]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
20/20 [==============================] - 3s 2ms/step - loss: 0.9000 - accuracy: 0.7274
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7323 - accuracy: 0.7726
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6212 - accuracy: 0.8194
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5364 - accuracy: 0.8323
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4708 - accuracy: 0.8468
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4147 - accuracy: 0.8597
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3672 - accuracy: 0.8806
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3275 - accuracy: 0.8806
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2963 - accuracy: 0.8887
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2685 - accuracy: 0.8952
Epoch 11/

# **Pruebas**

In [30]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
#np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1))1))

# **Matriz de Confusión**

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[91 10]
 [ 0 55]]


0.9358974358974359